//
// Created by wp on 2023/10/17.
//

#ifndef KSDIY_TEST_GPIO_H
#define KSDIY_TEST_GPIO_H

#include <esp_log.h>

static const char *TEST_GPIO_TAG = "test_gpio";

void test_gpio(void) {
    ESP_LOGI(TEST_GPIO_TAG, "ST7789_DC %d", CONFIG_ST7789_DC);
    ESP_LOGI(TEST_GPIO_TAG, "ST7789_CS %d", CONFIG_ST7789_CS);
    ESP_LOGI(TEST_GPIO_TAG, "ST7789_CLK %d", CONFIG_ST7789_CLK);
    ESP_LOGI(TEST_GPIO_TAG, "ST7789_MOSI %d", CONFIG_ST7789_MOSI);
    ESP_LOGI(TEST_GPIO_TAG, "ST7789_BLK %d", CONFIG_ST7789_BLK);

    ESP_LOGI(TEST_GPIO_TAG, "I2S_WS %d", CONFIG_I2S_WS);
    ESP_LOGI(TEST_GPIO_TAG, "I2S_SCK %d", CONFIG_I2S_SCK);
    ESP_LOGI(TEST_GPIO_TAG, "I2S_MIC %d", CONFIG_I2S_MIC);

    ESP_LOGI(TEST_GPIO_TAG, "2812 %d", CONFIG_2812);

    ESP_LOGI(TEST_GPIO_TAG, "SD_CLK %d", CONFIG_SD_CLK);
    ESP_LOGI(TEST_GPIO_TAG, "SD_MOSI %d", CONFIG_SD_MOSI);
    ESP_LOGI(TEST_GPIO_TAG, "SD_MISO %d", CONFIG_SD_MISO);
    ESP_LOGI(TEST_GPIO_TAG, "SD_CS %d", CONFIG_SD_CS);
}


#endif //KSDIY_TEST_GPIO_H
